- name: Add chroot configuration to sshd_config
  ansible.builtin.blockinfile:
    path: /etc/ssh/sshd_config
    block: |
      Port 22
      Port {{ ssh_alt_port }}
      Match LocalPort {{ ssh_alt_port }}
        ChrootDirectory {{ altroot }}/{{ zfs.zpool.name }}
        X11Forwarding no
        AllowTcpForwarding no
        PermitTTY yes
    create: yes
    insertafter: EOF

- name: Restart SSH service to apply changes
  ansible.builtin.service:
    name: sshd
    state: restarted