- name: configure pacman
  block:
    - lineinfile:
        path: /etc/pacman.conf
        regexp: '#Color'
        line: 'Color'
    - lineinfile:
        path: /etc/pacman.conf
        regexp: '#UseSyslog'
        line: 'UseSyslog'
    - lineinfile:
        path: /etc/pacman.conf
        regexp: '#CheckSpace'
        line: 'CheckSpace'
    - lineinfile:
        path: /etc/pacman.conf
        regexp: '#VerbosePkgLists'
        line: 'VerbosePkgLists'
    - lineinfile:
        path: /etc/pacman.conf
        regexp: '#ILoveCandy'
        line: 'ILoveCandy'
        insertafter: '# Misc options'
    - blockinfile:
        path: /etc/pacman.conf
        marker: "# {mark} pacman_conf_multilib ANSIBLE MANAGED BLOCK -->"
        block: |
          [multilib]
          Include = /etc/pacman.d/mirrorlist

- name: Remove pacman keys
  command: rm -rf /etc/pacman.d/gnupg

- name: Initialize pacman
  command: pacman-key --init

- name: Populate pacman keys
  command: pacman-key --populate archlinux

- name: Update repos
  pacman:
    update_cache: yes

- name: Initialize pacman
  command: pacman -S --noconfirm archlinux-keyring
  
- name: Install reflector
  pacman:
    name: reflector
    state: present

- name: Configure reflector
  copy:
    src: reflector.conf
    dest: /etc/xdg/reflector/
  notify: enable reflector

- name: Populate pacman keys
  command: reflector --latest 10 --protocol https --sort rate --save /etc/pacman.d/mirrorlist

- name: Update repos
  pacman:
    update_cache: yes

- name: Install pacman hooks
  pacman:
    name:
      - kernel-modules-hook # keep kernel modules dir after an upgrade

- name: Enable kernel modules cleanup
  systemd:
    name: linux-modules-cleanup
    enabled: yes
