---
- name: Debug disk partitions
  debug:
    var: disk_partitions

- name: Create LUKS containers
  luks_device:
    device: "{{ disk_partitions[item].root }}"
    name: "luks_{{ item | basename }}"
    passphrase: "{{ luks_passphrase }}"
    type: luks2
    cipher: aes-xts-plain64
    hash: sha512
    keysize: 512
    state: opened
  loop: "{{ disks }}"

- name: Verify LUKS containers are created and opened
  stat:
    path: "/dev/mapper/luks_{{ item | basename }}"
  register: luks_check
  loop: "{{ disks }}"
  failed_when: not luks_check.stat.exists