---
- name: Partition disks
  include_tasks: partition.yml

- name: Debug disk partitions after partitioning
  debug:
    var: disk_partitions

- name: Setup encryption
  include_tasks: encrypt.yml

- name: Create ZFS pool
  include_tasks: zfs.yml