---
- name: Build LUKS device list for ZFS
  set_fact:
    luks_device_paths: "{{ luks_device_paths | default([]) + ['/dev/mapper/luks_' + (item | basename)] }}"
  loop: "{{ disks }}"

- name: Debug LUKS device paths
  debug:
    var: luks_device_paths

- name: Verify LUKS devices exist
  stat:
    path: "{{ item }}"
  register: luks_device_check
  loop: "{{ luks_device_paths }}"
  failed_when: not luks_device_check.stat.exists

- name: Create ZFS pool
  command: >
    zpool create -f {{ zfs_pool_name }}
    -o ashift=13
    -o altroot={{ install_root }}
    -O compression=lz4
    -O atime=off
    -O xattr=sa
    -O acltype=posix
    -m none
    {{ zfs_pool_type if zfs_pool_type != 'stripe' else '' }}
    {{ luks_device_paths | join(' ') }}



- name: Create ZFS datasets
  zfs:
    name: "{{ zfs_pool_name }}/{{ item.name }}"
    state: present
    extra_zfs_properties: "{{ item.properties }}"
  loop:
    - name: ROOT
      properties:
        mountpoint: none
    - name: ROOT/default
      properties:
        mountpoint: /
    - name: home
      properties:
        mountpoint: /home
    - name: var
      properties:
        mountpoint: /var

- name: Set ZFS boot-filesystem
  command: zpool set bootfs={{ zfs_pool_name }}/ROOT/default {{ zfs_pool_name }}

- name: Unmount ZFS filesystems
  command: zfs umount -a
  
- name: Export zpool to that it can be imported to installed system
  command: zpool export -a
  ignore_errors: true
  

- name: Import zpool
  command: zpool import -R {{ install_root }} {{ zfs_pool_name }}

- name: Create zpool cache and copy to mounted zpool
  shell: '{{ item }}'
  loop:
    - mkdir -p /etc/zfs
    - mkdir -p {{ install_root }}/etc/zfs
    - zpool set cachefile=/etc/zfs/zpool.cache {{ zfs_pool_name }}
    - cp /etc/zfs/zpool.cache {{ install_root }}/etc/zfs/zpool.cache