---
- name: Install Arch Linux with ZFS
  hosts: localhost
  connection: local
  become: yes
  gather_facts: yes
  
  vars:
    install_root: /mnt
    zfs_pool_name: rpool
    luks_passphrase: "{{ vault_luks_passphrase | default('password') }}"
    hostname: "{{ target_hostname | default('archbox') }}"
    username: "{{ target_username | default('arch') }}"
    user_password: "{{ vault_user_password | default('password') }}"
    partition_helper:
    get_partition: |
      {% set ns = namespace(result=[]) %}
      {% for disk in disks %}
        {% set suffix = 'p' if 'nvme' in disk else '' %}
        {% set _ = ns.result.append({
          'disk': disk,
          'suffix': suffix,
          'efi': disk + suffix + '1',
          'root': disk + suffix + '2'
        }) %}
      {% endfor %}
      {{ ns.result }}

  tasks:
    - name: Prepare installation environment
      include_role:
        name: prepare-environment
        
    - name: Configure disks
      include_role:
        name: configure-disks
        
    - name: Install base system
      include_role:
        name: install-base-system
        
    - name: Configure chroot environment
      include_role:
        name: setup-chroot
        
    - name: Configure system (in chroot)
      include_role:
        name: configure-system
      vars:
        ansible_chroot: "{{ install_root }}"