---
- hosts: localhost
  name: Bootstrap Arch Linux system
  connection: local
  gather_facts: no
  
  vars:
    _allowed_envs:
      - dev
      - preprod
      - prod

  vars_prompt:
    - name: system_name
      prompt: "System hostname"
      private: no
      confirm: no
      
    - name: swap_size
      prompt: "System swap-size"
      private: no
      confirm: no
      
    - name: luks_passphrase
      prompt: "encryption passphrase"
      unsafe: yes
      private: yes
      confirm: yes
      
    - name: user_name
      prompt: "Username"
      private: no
      confirm: no
      
    - name: user_password
      prompt: "user password"
      encrypt: "sha512_crypt"
      unsafe: yes
      private: yes
      confirm: yes
      
  pre_tasks:
    - name: Validate swap is an integer
      fail:
        msg: >-
          Swap size is not formatted correctly. Please make sure it is of the form of an integer (GB).
      when: not swap_size is regex('\d*')
      run_once: true
      
  tasks:
    #- name: Print all available facts
    #  ansible.builtin.debug:
    #    var: ansible_facts
    #- name: "Ansible | List all known variables and facts"
    #  ansible.builtin.debug:
    #    var: hostvars[inventory_hostname]
    - name: "Ansible | List all known variables and facts"
      ansible.builtin.debug:
        var: vars
