---
# - name: Mount EFI partition
#   mount:
#     path: "{{ install_root }}/boot"
#     src: "{{ disk_partitions[disks[0]].efi }}"
#     fstype: vfat
#     state: mounted

- name: Mount EFI partition
  mount:
    path: "{{ install_root }}/boot"
    src: "{{ disks[0] }}p1"
    fstype: vfat
    state: mounted

- name: Install base system packages
  command: pacstrap {{ install_root }} base python zfs
  # python is required for Ansible modules

- name: Generate fstab
  shell: genfstab -U {{ install_root }} > {{ install_root }}/etc/fstab

- name: Install systemd-boot
  command: bootctl --path={{ install_root }}/boot install
  ignore_errors: true
  
- name: Copy pacman mirrorlist
  copy:
    src: /etc/pacman.d/mirrorlist
    dest: "{{ install_root }}/etc/pacman.d/mirrorlist"